"""add type db

Revision ID: 0e6a0499ac76
Revises: 322d8631a23f
Create Date: 2026-03-01 00:41:57.621890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6a0499ac76'
down_revision = '322d8631a23f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('db_type', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_db_type'), ['db_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_db_type'))
        batch_op.drop_column('db_type')

    # ### end Alembic commands ###
