"""add epname and efname

Revision ID: 2ec5b4cac8b3
Revises: b1bb7c6f2acc
Create Date: 2026-04-22 09:45:15.968922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec5b4cac8b3'
down_revision = 'b1bb7c6f2acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ePname', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('eFname', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_eFname'), ['eFname'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_ePname'), ['ePname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_ePname'))
        batch_op.drop_index(batch_op.f('ix_patients_eFname'))
        batch_op.drop_column('eFname')
        batch_op.drop_column('ePname')

    # ### end Alembic commands ###
