"""empty message

Revision ID: 322d8631a23f
Revises: 
Create Date: 2026-02-24 11:51:41.448083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322d8631a23f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manzor_p',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('m_name', sa.String(), nullable=True),
    sa.Column('mc_name', sa.String(), nullable=True),
    sa.Column('sell_p', sa.Integer(), nullable=True),
    sa.Column('c_p', sa.Integer(), nullable=True),
    sa.Column('d_m', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manzor_p', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manzor_p_c_p'), ['c_p'], unique=False)
        batch_op.create_index(batch_op.f('ix_manzor_p_d_m'), ['d_m'], unique=False)
        batch_op.create_index(batch_op.f('ix_manzor_p_m_name'), ['m_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_manzor_p_mc_name'), ['mc_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_manzor_p_quantity'), ['quantity'], unique=False)
        batch_op.create_index(batch_op.f('ix_manzor_p_sell_p'), ['sell_p'], unique=False)

    op.create_table('medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('m_name', sa.String(), nullable=True),
    sa.Column('mc_name', sa.String(), nullable=True),
    sa.Column('sell_p', sa.Integer(), nullable=True),
    sa.Column('c_p', sa.Integer(), nullable=True),
    sa.Column('d_m', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_c_p'), ['c_p'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_d_m'), ['d_m'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_m_name'), ['m_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_mc_name'), ['mc_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_quantity'), ['quantity'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_sell_p'), ['sell_p'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('fathername', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('p_fee', sa.Integer(), nullable=True),
    sa.Column('m_f', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('number', sa.String(length=10), nullable=True),
    sa.Column('p_number', sa.Integer(), nullable=True),
    sa.Column('u_s', sa.Integer(), nullable=True),
    sa.Column('neb', sa.String(), nullable=True),
    sa.Column('iv_c', sa.Integer(), nullable=True),
    sa.Column('im', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_fathername'), ['fathername'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_fee'), ['fee'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_im'), ['im'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_iv_c'), ['iv_c'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_m_f'), ['m_f'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_neb'), ['neb'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_p_fee'), ['p_fee'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_p_number'), ['p_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_u_s'), ['u_s'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_username'), ['username'], unique=False)

    op.create_table('cart_ms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('manzor_p_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manzor_p_id'], ['manzor_p.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carts')
    op.drop_table('cart_ms')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_username'))
        batch_op.drop_index(batch_op.f('ix_patients_u_s'))
        batch_op.drop_index(batch_op.f('ix_patients_p_number'))
        batch_op.drop_index(batch_op.f('ix_patients_p_fee'))
        batch_op.drop_index(batch_op.f('ix_patients_number'))
        batch_op.drop_index(batch_op.f('ix_patients_neb'))
        batch_op.drop_index(batch_op.f('ix_patients_m_f'))
        batch_op.drop_index(batch_op.f('ix_patients_iv_c'))
        batch_op.drop_index(batch_op.f('ix_patients_im'))
        batch_op.drop_index(batch_op.f('ix_patients_id'))
        batch_op.drop_index(batch_op.f('ix_patients_gender'))
        batch_op.drop_index(batch_op.f('ix_patients_fee'))
        batch_op.drop_index(batch_op.f('ix_patients_fathername'))
        batch_op.drop_index(batch_op.f('ix_patients_address'))

    op.drop_table('patients')
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_sell_p'))
        batch_op.drop_index(batch_op.f('ix_medicine_quantity'))
        batch_op.drop_index(batch_op.f('ix_medicine_mc_name'))
        batch_op.drop_index(batch_op.f('ix_medicine_m_name'))
        batch_op.drop_index(batch_op.f('ix_medicine_id'))
        batch_op.drop_index(batch_op.f('ix_medicine_d_m'))
        batch_op.drop_index(batch_op.f('ix_medicine_c_p'))

    op.drop_table('medicine')
    with op.batch_alter_table('manzor_p', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manzor_p_sell_p'))
        batch_op.drop_index(batch_op.f('ix_manzor_p_quantity'))
        batch_op.drop_index(batch_op.f('ix_manzor_p_mc_name'))
        batch_op.drop_index(batch_op.f('ix_manzor_p_m_name'))
        batch_op.drop_index(batch_op.f('ix_manzor_p_d_m'))
        batch_op.drop_index(batch_op.f('ix_manzor_p_c_p'))

    op.drop_table('manzor_p')
    # ### end Alembic commands ###
