"""add profit

Revision ID: 8e2e555901b9
Revises: 0e6a0499ac76
Create Date: 2026-03-02 00:54:45.179241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2e555901b9'
down_revision = '0e6a0499ac76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profit', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_profit'), ['profit'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_profit'))
        batch_op.drop_column('profit')

    # ### end Alembic commands ###
