"""add loan

Revision ID: b1bb7c6f2acc
Revises: 8e2e555901b9
Create Date: 2026-04-20 11:14:49.521169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1bb7c6f2acc'
down_revision = '8e2e555901b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_loan'), ['loan'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_loan'))
        batch_op.drop_column('loan')

    # ### end Alembic commands ###
