"""add epname and efname

Revision ID: ebf9fd08f8a5
Revises: 2ec5b4cac8b3
Create Date: 2026-06-28 14:06:13.531694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf9fd08f8a5'
down_revision = '2ec5b4cac8b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e_moneys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('e_m', sa.Integer(), nullable=False),
    sa.Column('e_r', sa.String(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('e_moneys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_e_moneys_e_m'), ['e_m'], unique=False)
        batch_op.create_index(batch_op.f('ix_e_moneys_e_r'), ['e_r'], unique=False)
        batch_op.create_index(batch_op.f('ix_e_moneys_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('e_moneys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_e_moneys_id'))
        batch_op.drop_index(batch_op.f('ix_e_moneys_e_r'))
        batch_op.drop_index(batch_op.f('ix_e_moneys_e_m'))

    op.drop_table('e_moneys')
    # ### end Alembic commands ###
